import type { ComponentType } from 'react';

/**
 * NCS 반도체 학습모듈 MDX 로더 레지스트리.
 * 동적 라우트(`/sources/ncs-semi/[module]`)에서 MDX를 직접 import할 수 없어 로더 맵을 쓴다.
 * 확장: 새 모듈 `{module}.mdx` 작성 후 여기에 한 줄 등록 (컴포넌트/페이지 코어 무수정).
 */
const loaders: Record<string, () => Promise<{ default: ComponentType }>> = {
  'product-planning': () => import('@/content/sources/ncs-semi/product-planning.mdx'),
  'architecture-design': () => import('@/content/sources/ncs-semi/architecture-design.mdx'),
  'digital-circuit-design': () => import('@/content/sources/ncs-semi/digital-circuit-design.mdx'),
  'custom-layout-process-analysis': () => import('@/content/sources/ncs-semi/custom-layout-process-analysis.mdx'),
  'custom-layout-verification': () => import('@/content/sources/ncs-semi/custom-layout-verification.mdx'),
  'system-process-development': () => import('@/content/sources/ncs-semi/system-process-development.mdx'),
  'firmware-development': () => import('@/content/sources/ncs-semi/firmware-development.mdx'),
  'package-product-design': () => import('@/content/sources/ncs-semi/package-product-design.mdx'),
  'flip-package-development': () => import('@/content/sources/ncs-semi/flip-package-development.mdx'),
  'reliability-testing': () => import('@/content/sources/ncs-semi/reliability-testing.mdx'),
  'advanced-underfill-package': () => import('@/content/sources/ncs-semi/advanced-underfill-package.mdx'),
  'photo-equipment': () => import('@/content/sources/ncs-semi/photo-equipment.mdx'),
  'quality-control': () => import('@/content/sources/ncs-semi/quality-control.mdx'),
  'productivity': () => import('@/content/sources/ncs-semi/productivity.mdx'),
  'thinfilm-diffusion-equipment': () => import('@/content/sources/ncs-semi/thinfilm-diffusion-equipment.mdx'),
  'cleanroom-facility': () => import('@/content/sources/ncs-semi/cleanroom-facility.mdx'),
  'package-level-test': () => import('@/content/sources/ncs-semi/package-level-test.mdx'),
  'etch-equipment': () => import('@/content/sources/ncs-semi/etch-equipment.mdx'),
  'clean-cmp-equipment': () => import('@/content/sources/ncs-semi/clean-cmp-equipment.mdx'),
  'metrology-equipment': () => import('@/content/sources/ncs-semi/metrology-equipment.mdx'),
  'wafer-level-test': () => import('@/content/sources/ncs-semi/wafer-level-test.mdx'),
  'packaging-front-equipment': () => import('@/content/sources/ncs-semi/packaging-front-equipment.mdx'),
  'packaging-back-equipment': () => import('@/content/sources/ncs-semi/packaging-back-equipment.mdx'),
  'utility-operation': () => import('@/content/sources/ncs-semi/utility-operation.mdx'),
  'equipment-concept-design': () => import('@/content/sources/ncs-semi/equipment-concept-design.mdx'),
  'equipment-main-design': () => import('@/content/sources/ncs-semi/equipment-main-design.mdx'),
  'equipment-electrical-design': () => import('@/content/sources/ncs-semi/equipment-electrical-design.mdx'),
  'equipment-board-design': () => import('@/content/sources/ncs-semi/equipment-board-design.mdx'),
  'equipment-system-software': () => import('@/content/sources/ncs-semi/equipment-system-software.mdx'),
  'equipment-utility-software': () => import('@/content/sources/ncs-semi/equipment-utility-software.mdx'),
  'equipment-outsourcing': () => import('@/content/sources/ncs-semi/equipment-outsourcing.mdx'),
  'equipment-prototype-evaluation': () => import('@/content/sources/ncs-semi/equipment-prototype-evaluation.mdx'),
  'equipment-quality-control': () => import('@/content/sources/ncs-semi/equipment-quality-control.mdx'),
  'equipment-customer-support': () => import('@/content/sources/ncs-semi/equipment-customer-support.mdx'),
  'equipment-mechanical-assembly': () => import('@/content/sources/ncs-semi/equipment-mechanical-assembly.mdx'),
  'equipment-electrical-verification': () => import('@/content/sources/ncs-semi/equipment-electrical-verification.mdx'),
  'vacuum-plasma-maintenance': () => import('@/content/sources/ncs-semi/vacuum-plasma-maintenance.mdx'),
  'chemical-gas-maintenance': () => import('@/content/sources/ncs-semi/chemical-gas-maintenance.mdx'),
  'equipment-safety': () => import('@/content/sources/ncs-semi/equipment-safety.mdx'),
  'cleaning-process-gas': () => import('@/content/sources/ncs-semi/cleaning-process-gas.mdx'),
  'material-safety': () => import('@/content/sources/ncs-semi/material-safety.mdx'),
  'wafer-materials': () => import('@/content/sources/ncs-semi/wafer-materials.mdx'),
  'cmp-materials': () => import('@/content/sources/ncs-semi/cmp-materials.mdx'),
  'cleaning-materials': () => import('@/content/sources/ncs-semi/cleaning-materials.mdx'),
  'flipchip-materials': () => import('@/content/sources/ncs-semi/flipchip-materials.mdx'),
  'mask-materials': () => import('@/content/sources/ncs-semi/mask-materials.mdx'),
  'cmp-slurry-materials': () => import('@/content/sources/ncs-semi/cmp-slurry-materials.mdx'),
  'materials-quality-control': () => import('@/content/sources/ncs-semi/materials-quality-control.mdx'),
  'lithography-materials': () => import('@/content/sources/ncs-semi/lithography-materials.mdx'),
  'photo-process-materials': () => import('@/content/sources/ncs-semi/photo-process-materials.mdx'),
  'track-process-materials': () => import('@/content/sources/ncs-semi/track-process-materials.mdx'),
  'wet-chemical-materials': () => import('@/content/sources/ncs-semi/wet-chemical-materials.mdx'),
  'gas-materials': () => import('@/content/sources/ncs-semi/gas-materials.mdx'),
  'etching-process-gas': () => import('@/content/sources/ncs-semi/etching-process-gas.mdx'),
  'thinfilm-process-gas': () => import('@/content/sources/ncs-semi/thinfilm-process-gas.mdx'),
  'implant-process-gas': () => import('@/content/sources/ncs-semi/implant-process-gas.mdx'),
  'package-materials': () => import('@/content/sources/ncs-semi/package-materials.mdx'),
  'metal-target-materials': () => import('@/content/sources/ncs-semi/metal-target-materials.mdx'),
  'sod-process-materials': () => import('@/content/sources/ncs-semi/sod-process-materials.mdx'),
  'materials-production-control': () => import('@/content/sources/ncs-semi/materials-production-control.mdx'),
  'equipment-design': () => import('@/content/sources/ncs-semi/equipment-design.mdx'),
  'equipment-assembly': () => import('@/content/sources/ncs-semi/equipment-assembly.mdx'),
  'equipment-electrical-assembly': () => import('@/content/sources/ncs-semi/equipment-electrical-assembly.mdx'),
  'optical-equipment-maintenance': () => import('@/content/sources/ncs-semi/optical-equipment-maintenance.mdx'),
  'thinfilm-precursor': () => import('@/content/sources/ncs-semi/thinfilm-precursor.mdx'),
  'analog-circuit-design': () => import('@/content/sources/ncs-semi/analog-circuit-design.mdx'),
  'analog-architecture-design': () => import('@/content/sources/ncs-semi/analog-architecture-design.mdx'),
  'analog-device-design': () => import('@/content/sources/ncs-semi/analog-device-design.mdx'),
  'analog-system-design': () => import('@/content/sources/ncs-semi/analog-system-design.mdx'),
  'design-verification': () => import('@/content/sources/ncs-semi/design-verification.mdx'),
  'auto-layout-design': () => import('@/content/sources/ncs-semi/auto-layout-design.mdx'),
  'custom-layout-design': () => import('@/content/sources/ncs-semi/custom-layout-design.mdx'),
  'process-development': () => import('@/content/sources/ncs-semi/process-development.mdx'),
  'memory-process-development': () => import('@/content/sources/ncs-semi/memory-process-development.mdx'),
  'unit-process-development': () => import('@/content/sources/ncs-semi/unit-process-development.mdx'),
  'package-assembly-development': () => import('@/content/sources/ncs-semi/package-assembly-development.mdx'),
  'wirebond-package-development': () => import('@/content/sources/ncs-semi/wirebond-package-development.mdx'),
  'wafer-level-package': () => import('@/content/sources/ncs-semi/wafer-level-package.mdx'),
  'fanout-package': () => import('@/content/sources/ncs-semi/fanout-package.mdx'),
  'heterogeneous-package': () => import('@/content/sources/ncs-semi/heterogeneous-package.mdx'),
  'product-verification': () => import('@/content/sources/ncs-semi/product-verification.mdx'),
  'environmental-testing': () => import('@/content/sources/ncs-semi/environmental-testing.mdx'),
  'lifetime-testing': () => import('@/content/sources/ncs-semi/lifetime-testing.mdx'),
  'robustness-testing': () => import('@/content/sources/ncs-semi/robustness-testing.mdx'),
};

export async function loadNcsModuleMdx(moduleId: string): Promise<ComponentType | null> {
  const loader = loaders[moduleId];
  if (!loader) return null;
  const mod = await loader();
  return mod.default;
}
