/**
 * 자료원(Source) 레지스트리
 * Design: docs/02-design/features/multi-source-learning-platform.design.md §3.1
 *
 * - EPI_BOOK: 「반도체 산업의 유해인자」 (윤충식 외) — 17 챕터를 SourceSection으로 노출
 * - OSHA_SCS: OSHA Semiconductor Chemical Safety 5 Part — Phase B에서 본문 추가
 */

import { chapters } from './chapters';
import type { Chapter, Source, SourceSection } from './types';

function chapterToSection(c: Chapter): SourceSection {
  return {
    id: c.id,
    href: c.legacyUrl ?? `/chapter/${c.slug}/`,
    title: c.title,
    summary: c.subtitle,
    readingTime: c.readingTime,
  };
}

export const EPI_BOOK: Source = {
  id: 'epi-semi-hazards',
  kind: 'book',
  language: 'ko',
  title: '반도체 산업의 유해인자',
  subtitle: '학술서 — 윤충식 외 6인 공저',
  attribution: '윤충식·김승원·박동욱·정지연·최상준·하권철·함승헌',
  publisher: '에피스테메',
  year: 2021,
  license: 'fair-use',
  order: 1,
  accent: 'book',
  sections: chapters.map(chapterToSection),
};

export const OSHA_SCS: Source = {
  id: 'osha-scs',
  kind: 'training-program',
  language: 'en',
  title: 'Semiconductor Chemical Safety',
  subtitle: 'OSHA training program · Parts 1A–4',
  attribution: 'U.S. OSHA (Occupational Safety and Health Administration)',
  publisher: 'United States Department of Labor',
  year: 2024,
  license: 'us-gov-public-domain',
  url: 'https://www.osha.gov/',
  order: 2,
  accent: 'osha',
  sections: [
    {
      id: 'part-1a',
      href: '/sources/osha-scs/part-1a/',
      title: 'Part 1A · Introduction to GHS',
      summary: 'GHS 화학물질 분류·라벨 체계 기초',
      readingTime: 22,
    },
    {
      id: 'part-1b',
      href: '/sources/osha-scs/part-1b/',
      title: 'Part 1B · Communication, Controls, and Emergency Procedures',
      summary: '위험 전달, 통제, 비상 대응 절차',
      readingTime: 24,
    },
    {
      id: 'part-2',
      href: '/sources/osha-scs/part-2/',
      title: 'Part 2 · Chemical Hazards, Controls, and Emergency Actions',
      summary: '인화·부식·독성 등 화학물질 위험 분류와 대응',
      readingTime: 33,
    },
    {
      id: 'part-3',
      href: '/sources/osha-scs/part-3/',
      title: 'Part 3 · Extremely Hazardous Chemicals',
      summary: '실란 등 9개 극위험 화학물질 카테고리',
      readingTime: 24,
    },
    {
      id: 'part-4',
      href: '/sources/osha-scs/part-4/',
      title: 'Part 4 · Hazardous Gas Systems and Controls',
      summary: '압축가스·극저온 가스 시스템과 통제 절차',
      readingTime: 26,
    },
  ],
};

/**
 * NCS 반도체 학습모듈 — 국가직무능력표준(교육부·한국산업인력공단).
 * 원자료 `data/ncs/`(직무훈련용)를 고등학생 눈높이로 재구성. 원문 이미지는 저작권상 미사용.
 * 파일럿: 반도체제조 트랙 3개 → 세분류(개발·재료·장비)별 확대.
 * 확장: `src/content/sources/ncs-semi/{module}.mdx` 작성 + `ncsMdx.tsx` 로더 등록 + 아래 sections에 추가.
 */
export const NCS_SEMI: Source = {
  id: 'ncs-semi',
  kind: 'standard',
  language: 'ko',
  title: 'NCS 반도체 학습모듈',
  subtitle: '국가직무능력표준 — 현장 직무로 배우는 반도체',
  attribution: '교육부 · 한국산업인력공단',
  publisher: 'NCS 국가직무능력표준',
  year: 2024,
  license: 'ncs-open',
  url: 'https://www.ncs.go.kr/',
  order: 3,
  accent: 'standard',
  sections: [
    {
      id: 'product-planning',
      href: '/sources/ncs-semi/product-planning/',
      title: '반도체 제품 기획',
      summary: '시장·기술·손익을 읽어 어떤 칩을 만들지 결정하는 일',
      readingTime: 11,
      group: '반도체개발',
    },
    {
      id: 'architecture-design',
      href: '/sources/ncs-semi/architecture-design/',
      title: '반도체 아키텍처 설계',
      summary: '만들 칩의 사양을 정하고 전체 구조를 그리는 일',
      readingTime: 10,
      group: '반도체개발',
    },
    {
      id: 'digital-circuit-design',
      href: '/sources/ncs-semi/digital-circuit-design/',
      title: '디지털 회로 설계',
      summary: 'HDL 코드로 회로를 쓰고 시뮬레이션으로 검증하는 일',
      readingTime: 10,
      group: '반도체개발',
    },
    {
      id: 'analog-circuit-design',
      href: '/sources/ncs-semi/analog-circuit-design/',
      title: '아날로그 회로 설계',
      summary: '연속 신호를 다루는 아날로그 회로를 그리고 시뮬레이션으로 검증하는 일',
      readingTime: 11,
      group: '반도체개발',
    },
    {
      id: 'analog-architecture-design',
      href: '/sources/ncs-semi/analog-architecture-design/',
      title: '아날로그 회로 아키텍처 설계',
      summary: '아날로그 칩의 블록 구성과 전체 구조를 정하는 상위 설계를 그리는 일',
      readingTime: 10,
      group: '반도체개발',
    },
    {
      id: 'analog-device-design',
      href: '/sources/ncs-semi/analog-device-design/',
      title: '아날로그 회로 소자 레벨 설계',
      summary: '트랜지스터 하나하나의 크기를 정해 회로를 소자 수준으로 완성하는 일',
      readingTime: 9,
      group: '반도체개발',
    },
    {
      id: 'analog-system-design',
      href: '/sources/ncs-semi/analog-system-design/',
      title: '아날로그 회로 시스템 설계',
      summary: '완성된 회로를 보드로 검증하고 IP로 포장해 양산까지 내보내는 일',
      readingTime: 11,
      group: '반도체개발',
    },
    {
      id: 'design-verification',
      href: '/sources/ncs-semi/design-verification/',
      title: '반도체 설계 검증',
      summary: '설계한 회로가 사양대로 동작하는지 계획을 세워 시뮬레이션으로 확인하는 일',
      readingTime: 10,
      group: '반도체개발',
    },
    {
      id: 'auto-layout-design',
      href: '/sources/ncs-semi/auto-layout-design/',
      title: '자동 배치 배선 레이아웃 설계',
      summary: 'EDA 툴로 소자를 자동 배치·배선하고 기생 효과까지 관리하는 일',
      readingTime: 10,
      group: '반도체개발',
    },
    {
      id: 'custom-layout-design',
      href: '/sources/ncs-semi/custom-layout-design/',
      title: '커스텀 레이아웃 설계',
      summary: '트랜지스터와 배선을 사람 손으로 직접 배치·배선하는 풀 커스텀 작업',
      readingTime: 10,
      group: '반도체개발',
    },
    {
      id: 'custom-layout-process-analysis',
      href: '/sources/ncs-semi/custom-layout-process-analysis/',
      title: '커스텀 레이아웃 적용 공정 분석',
      summary: '레이아웃을 그리기 전에 적용할 공정의 소자·레이어를 분석하는 일',
      readingTime: 10,
      group: '반도체개발',
    },
    {
      id: 'custom-layout-verification',
      href: '/sources/ncs-semi/custom-layout-verification/',
      title: '커스텀 레이아웃 검증',
      summary: '그린 도면이 공장의 규칙과 회로에 맞는지 DRC·LVS로 확인하는 일',
      readingTime: 9,
      group: '반도체개발',
    },
    {
      id: 'process-development',
      href: '/sources/ncs-semi/process-development/',
      title: '반도체 제조 공정 개발',
      summary: '새 칩에 맞는 제조 공정 흐름을 설계하고 신뢰성까지 검증하는 일',
      readingTime: 10,
      group: '반도체개발',
    },
    {
      id: 'system-process-development',
      href: '/sources/ncs-semi/system-process-development/',
      title: '시스템 반도체 제조 공정 개발',
      summary: '트랜지스터가 만들어지는 공정 흐름을 설계하고 검증하는 일',
      readingTime: 10,
      group: '반도체개발',
    },
    {
      id: 'memory-process-development',
      href: '/sources/ncs-semi/memory-process-development/',
      title: '메모리 반도체 제조 공정 개발',
      summary: '웰부터 게이트·배선까지 메모리 칩의 제조 공정을 개발하는 일',
      readingTime: 12,
      group: '반도체개발',
    },
    {
      id: 'unit-process-development',
      href: '/sources/ncs-semi/unit-process-development/',
      title: '반도체 제조 단위 공정 개발',
      summary: '식각·증착·이온 주입 같은 단위 공정 하나하나를 개발·최적화하는 일',
      readingTime: 9,
      group: '반도체개발',
    },
    {
      id: 'firmware-development',
      href: '/sources/ncs-semi/firmware-development/',
      title: '반도체 펌웨어 개발',
      summary: '칩을 깨우고 움직이는 가장 낮은 층의 소프트웨어를 만드는 일',
      readingTime: 10,
      group: '반도체개발',
    },
    {
      id: 'package-product-design',
      href: '/sources/ncs-semi/package-product-design/',
      title: '패키지 제품설계',
      summary: '칩을 보호하고 연결하는 패키지를 전기·열·기계 균형으로 설계하는 일',
      readingTime: 10,
      group: '반도체개발',
    },
    {
      id: 'package-assembly-development',
      href: '/sources/ncs-semi/package-assembly-development/',
      title: '패키지 조립 공정 개발',
      summary: '웨이퍼 연삭부터 솔더 범핑·리드 성형까지 조립 공정을 개발하는 일',
      readingTime: 11,
      group: '반도체개발',
    },
    {
      id: 'wirebond-package-development',
      href: '/sources/ncs-semi/wirebond-package-development/',
      title: '와이어 본딩 패키지 개발',
      summary: '금선으로 칩과 리드 프레임을 이어 붙이는 패키지를 개발하는 일',
      readingTime: 11,
      group: '반도체개발',
    },
    {
      id: 'flip-package-development',
      href: '/sources/ncs-semi/flip-package-development/',
      title: '플립 패키지 개발',
      summary: '칩을 뒤집어 기판에 직접 붙이는 첨단 패키지를 개발하는 일',
      readingTime: 10,
      group: '반도체개발',
    },
    {
      id: 'wafer-level-package',
      href: '/sources/ncs-semi/wafer-level-package/',
      title: '웨이퍼 레벨 패키지 개발',
      summary: '웨이퍼를 자르지 않은 채 재배선과 범핑까지 마치는 패키지를 만드는 일',
      readingTime: 11,
      group: '반도체개발',
    },
    {
      id: 'fanout-package',
      href: '/sources/ncs-semi/fanout-package/',
      title: '어드밴스드 팬 아웃 패키지 개발',
      summary: '칩 바깥까지 배선을 넓혀 입출력 단자를 늘리는 팬 아웃 패키지를 만드는 일',
      readingTime: 10,
      group: '반도체개발',
    },
    {
      id: 'heterogeneous-package',
      href: '/sources/ncs-semi/heterogeneous-package/',
      title: '이종 접합 패키지 개발',
      summary: '서로 다른 칩을 TSV·하이브리드 본딩으로 쌓아 한 패키지로 묶는 일',
      readingTime: 11,
      group: '반도체개발',
    },
    {
      id: 'product-verification',
      href: '/sources/ncs-semi/product-verification/',
      title: '반도체 제품 기능·성능 검증',
      summary: '완성된 칩의 기능과 성능을 시험해 출하할 수 있는지 판정하는 일',
      readingTime: 11,
      group: '반도체개발',
    },
    {
      id: 'reliability-testing',
      href: '/sources/ncs-semi/reliability-testing/',
      title: '반도체 신뢰성 평가',
      summary: '몇 년 뒤의 고장을 실험실에서 미리 만들어 수명을 예측·보증하는 일',
      readingTime: 10,
      group: '반도체개발',
    },
    {
      id: 'advanced-underfill-package',
      href: '/sources/ncs-semi/advanced-underfill-package/',
      title: '어드밴스드 언더필 패키지 개발',
      summary: '칩과 기판 사이 빈틈을 채우는 언더필 공법을 고르고 개발하는 일',
      readingTime: 11,
      group: '반도체개발',
    },
    {
      id: 'environmental-testing',
      href: '/sources/ncs-semi/environmental-testing/',
      title: '반도체 환경 시험',
      summary: '온도·습도·진동·충격을 실험실에서 재현해 제품이 버티는지 확인하는 일',
      readingTime: 10,
      group: '반도체개발',
    },
    {
      id: 'lifetime-testing',
      href: '/sources/ncs-semi/lifetime-testing/',
      title: '반도체 수명 시험',
      summary: '높은 온도·전압으로 시간을 압축해 반도체의 수명을 미리 예측하는 일',
      readingTime: 9,
      group: '반도체개발',
    },
    {
      id: 'robustness-testing',
      href: '/sources/ncs-semi/robustness-testing/',
      title: '반도체 내성 시험',
      summary: '정전기·래치업 같은 순간 전기 충격을 버티는지 시험하고 분석하는 일',
      readingTime: 11,
      group: '반도체개발',
    },
    {
      id: 'photo-equipment',
      href: '/sources/ncs-semi/photo-equipment/',
      title: 'Photo(노광) 장비 운영',
      summary: '빛으로 회로를 그리는 노광·트랙 장비를 셋업하고 관리하는 일',
      readingTime: 12,
      group: '반도체제조',
    },
    {
      id: 'etch-equipment',
      href: '/sources/ncs-semi/etch-equipment/',
      title: 'Etch(식각) 장비 운영',
      summary: '식각 장비를 안전한 순서로 세우고 켜고, 닳는 부품을 미리 갈아주는 일',
      readingTime: 10,
      group: '반도체제조',
    },
    {
      id: 'clean-cmp-equipment',
      href: '/sources/ncs-semi/clean-cmp-equipment/',
      title: 'C&C(세정·CMP) 장비 운영',
      summary: '웨이퍼를 씻는 세정 장비와 표면을 평평하게 연마하는 CMP 장비를 셋업·관리하는 일',
      readingTime: 10,
      group: '반도체제조',
    },
    {
      id: 'metrology-equipment',
      href: '/sources/ncs-semi/metrology-equipment/',
      title: 'MI(계측·검사) 장비 운영',
      summary: '패터닝 뒤 박막 두께·미세 결함을 재는 계측·검사 장비를 도입·운영하는 일',
      readingTime: 10,
      group: '반도체제조',
    },
    {
      id: 'quality-control',
      href: '/sources/ncs-semi/quality-control/',
      title: '반도체 품질관리',
      summary: '불량을 찾아내고 원인을 되짚어 수율을 지키는 일',
      readingTime: 10,
      group: '반도체제조',
    },
    {
      id: 'productivity',
      href: '/sources/ncs-semi/productivity/',
      title: '반도체 생산성 향상',
      summary: '같은 설비에서 더 많은 좋은 칩을 만들어 내는 개선 활동',
      readingTime: 9,
      group: '반도체제조',
    },
    {
      id: 'thinfilm-diffusion-equipment',
      href: '/sources/ncs-semi/thinfilm-diffusion-equipment/',
      title: '박막·확산 장비 운영',
      summary: '웨이퍼에 막을 입히고 불순물을 넣는 고온 장비를 셋업·운영하는 일',
      readingTime: 10,
      group: '반도체제조',
    },
    {
      id: 'cleanroom-facility',
      href: '/sources/ncs-semi/cleanroom-facility/',
      title: '반도체 클린룸 시설 운영',
      summary: '반도체가 태어나는 초청정 공간의 공기·압력·에너지를 관리하는 일',
      readingTime: 10,
      group: '반도체제조',
    },
    {
      id: 'wafer-level-test',
      href: '/sources/ncs-semi/wafer-level-test/',
      title: '반도체 웨이퍼 레벨 테스트 장비 운영',
      summary: '웨이퍼 상태 그대로 칩을 찔러 양품·불량을 가려내는 EDS 검사 장비를 운영하는 일',
      readingTime: 11,
      group: '반도체제조',
    },
    {
      id: 'package-level-test',
      href: '/sources/ncs-semi/package-level-test/',
      title: '반도체 패키지 레벨 테스트 장비 운영',
      summary: '완성된 칩을 전기로 검사하는 ATE·핸들러 장비를 설치·교정·관리하는 일',
      readingTime: 11,
      group: '반도체제조',
    },
    {
      id: 'packaging-front-equipment',
      href: '/sources/ncs-semi/packaging-front-equipment/',
      title: '반도체 패키징 전공정 장비 운영',
      summary: '웨이퍼를 원하는 두께로 갈아내고(백그라인딩) 낱개 칩으로 잘라내는(소잉) 장비를 운영하는 일',
      readingTime: 11,
      group: '반도체제조',
    },
    {
      id: 'packaging-back-equipment',
      href: '/sources/ncs-semi/packaging-back-equipment/',
      title: '반도체 패키징 후공정 장비 운영',
      summary: '다이본딩·와이어본딩·몰딩·솔더볼 장비로 낱개 칩을 완성품으로 만드는 일',
      readingTime: 11,
      group: '반도체제조',
    },
    {
      id: 'utility-operation',
      href: '/sources/ncs-semi/utility-operation/',
      title: '반도체 유틸리티 운영',
      summary: '전기·가스·약품·초순수를 공장 구석구석 안전하게 실어 나르는 공급 계통을 관리하는 일',
      readingTime: 12,
      group: '반도체제조',
    },
    {
      id: 'material-safety',
      href: '/sources/ncs-semi/material-safety/',
      title: '반도체 재료 안전관리',
      summary: 'MSDS부터 폐기물까지 — 화학 재료의 위험을 알고 재고 대비하는 일',
      readingTime: 10,
      group: '반도체재료',
    },
    {
      id: 'wafer-materials',
      href: '/sources/ncs-semi/wafer-materials/',
      title: '반도체용 웨이퍼 재료 제조',
      summary: '녹인 실리콘에서 잉곳을 키워 웨이퍼 한 장으로 완성하는 재료의 출발점',
      readingTime: 12,
      group: '반도체재료',
    },
    {
      id: 'lithography-materials',
      href: '/sources/ncs-semi/lithography-materials/',
      title: '반도체용 리소그래피 재료 제조',
      summary: '감광제(PR)·현상액 등 회로를 웨이퍼에 새기는 리소그래피 재료를 만드는 일',
      readingTime: 12,
      group: '반도체재료',
    },
    {
      id: 'photo-process-materials',
      href: '/sources/ncs-semi/photo-process-materials/',
      title: '반도체용 포토 공정 재료 제조',
      summary: '빛에 반응해 회로를 새기는 감광제(PR)의 조성과 감광 원리를 다루는 일',
      readingTime: 12,
      group: '반도체재료',
    },
    {
      id: 'track-process-materials',
      href: '/sources/ncs-semi/track-process-materials/',
      title: '반도체용 트랙 공정 재료 제조',
      summary: '감광제를 도포·현상하는 트랙 공정용 씨너·현상액·BARC를 만드는 일',
      readingTime: 11,
      group: '반도체재료',
    },
    {
      id: 'cmp-materials',
      href: '/sources/ncs-semi/cmp-materials/',
      title: '반도체용 CMP 재료 제조',
      summary: '웨이퍼를 평평하게 깎는 슬러리를 만들고 품질을 지키는 일',
      readingTime: 11,
      group: '반도체재료',
    },
    {
      id: 'cleaning-materials',
      href: '/sources/ncs-semi/cleaning-materials/',
      title: '반도체용 세정 공정 재료 제조',
      summary: '웨이퍼를 씻는 화학약품을 표준 레시피로 배합해 만드는 일',
      readingTime: 10,
      group: '반도체재료',
    },
    {
      id: 'wet-chemical-materials',
      href: '/sources/ncs-semi/wet-chemical-materials/',
      title: '반도체용 습식화공약품 재료 제조',
      summary: '세정·식각에 쓰는 산·염기·용제를 초고순도로 정제해 만드는 일',
      readingTime: 12,
      group: '반도체재료',
    },
    {
      id: 'cleaning-process-gas',
      href: '/sources/ncs-semi/cleaning-process-gas/',
      title: '반도체용 세정 공정 가스 제조',
      summary: '웨이퍼를 씻는 특수가스를 초고순도(5N)로 합성·정제하는 일',
      readingTime: 9,
      group: '반도체재료',
    },
    {
      id: 'gas-materials',
      href: '/sources/ncs-semi/gas-materials/',
      title: '반도체용 가스 재료 제조',
      summary: '수백 종 특수가스를 초고순도로 만들어 안전하게 공급하는 일',
      readingTime: 12,
      group: '반도체재료',
    },
    {
      id: 'etching-process-gas',
      href: '/sources/ncs-semi/etching-process-gas/',
      title: '반도체용 식각 공정 가스 제조',
      summary: '실리콘·산화막을 깎는 식각용 특수가스를 만들고 순도를 지키는 일',
      readingTime: 11,
      group: '반도체재료',
    },
    {
      id: 'thinfilm-process-gas',
      href: '/sources/ncs-semi/thinfilm-process-gas/',
      title: '반도체용 박막 공정 가스 제조',
      summary: '웨이퍼에 막을 입히는 증착용 소스가스를 합성·정제하는 일',
      readingTime: 12,
      group: '반도체재료',
    },
    {
      id: 'implant-process-gas',
      href: '/sources/ncs-semi/implant-process-gas/',
      title: '반도체용 이온 주입 공정 가스 제조',
      summary: '불순물을 심는 이온주입용 도펀트 가스를 만들고 독성을 관리하는 일',
      readingTime: 12,
      group: '반도체재료',
    },
    {
      id: 'flipchip-materials',
      href: '/sources/ncs-semi/flipchip-materials/',
      title: '반도체용 플립칩 재료 제조',
      summary: '범프·언더필 등 플립칩 패키지 재료를 만들고 신뢰성을 시험하는 일',
      readingTime: 9,
      group: '반도체재료',
    },
    {
      id: 'package-materials',
      href: '/sources/ncs-semi/package-materials/',
      title: '반도체 패키지 재료 제조',
      summary: '리드프레임·본딩와이어·EMC 등 칩을 감싸는 패키지 재료를 만드는 일',
      readingTime: 12,
      group: '반도체재료',
    },
    {
      id: 'mask-materials',
      href: '/sources/ncs-semi/mask-materials/',
      title: '반도체용 마스크 재료 제조',
      summary: '회로 원본을 담는 석영 기판·크로뮴 막·펠리클 재료를 만드는 일',
      readingTime: 9,
      group: '반도체재료',
    },
    {
      id: 'cmp-slurry-materials',
      href: '/sources/ncs-semi/cmp-slurry-materials/',
      title: '반도체용 CMP 슬러리 재료 제조',
      summary: '나노 연마 입자를 합성해 실험실 레시피를 양산 슬러리로 키워 내는 일',
      readingTime: 10,
      group: '반도체재료',
    },
    {
      id: 'metal-target-materials',
      href: '/sources/ncs-semi/metal-target-materials/',
      title: '반도체용 금속 Target 재료 제조',
      summary: '배선을 만드는 스퍼터링용 금속 타깃 재료와 그 신뢰성을 다루는 일',
      readingTime: 12,
      group: '반도체재료',
    },
    {
      id: 'sod-process-materials',
      href: '/sources/ncs-semi/sod-process-materials/',
      title: '반도체용 SOD 공정 재료 제조',
      summary: '스핀 코팅으로 좁은 틈을 메우는 액상 절연막(SOD) 재료를 만드는 일',
      readingTime: 10,
      group: '반도체재료',
    },
    {
      id: 'materials-quality-control',
      href: '/sources/ncs-semi/materials-quality-control/',
      title: '반도체 재료 품질관리',
      summary: '재료 공급사가 자사 재료를 검사하고 고객 클레임에 대응하는 일',
      readingTime: 11,
      group: '반도체재료',
    },
    {
      id: 'materials-production-control',
      href: '/sources/ncs-semi/materials-production-control/',
      title: '반도체 재료 생산관리',
      summary: '재료 공장의 생산 계획·가동률·설비보전을 관리해 납기를 맞추는 일',
      readingTime: 13,
      group: '반도체재료',
    },
    {
      id: 'thinfilm-precursor',
      href: '/sources/ncs-semi/thinfilm-precursor/',
      title: '반도체용 박막 공정 전구체 제조',
      summary: '웨이퍼 위에 쌓일 막의 원료가 되는 고순도 화학 물질을 합성·정제하는 일',
      readingTime: 10,
      group: '반도체재료',
    },
    {
      id: 'equipment-concept-design',
      href: '/sources/ncs-semi/equipment-concept-design/',
      title: '반도체 장비 콘셉트 설계',
      summary: '고객 요구를 캐묻고 스펙을 숫자로 못 박아 장비의 밑그림을 그리는 일',
      readingTime: 9,
      group: '반도체장비',
    },
    {
      id: 'equipment-main-design',
      href: '/sources/ncs-semi/equipment-main-design/',
      title: '반도체 장비 주요부 기구 설계',
      summary: '노광장치를 예로, 장비의 핵심 기구부를 사양부터 도면까지 완성하는 일',
      readingTime: 10,
      group: '반도체장비',
    },
    {
      id: 'equipment-design',
      href: '/sources/ncs-semi/equipment-design/',
      title: '반도체 장비 주변부 기구 설계',
      summary: '장비를 둘러싼 부대 기구를 설계하고 시뮬레이션으로 검증하는 일',
      readingTime: 9,
      group: '반도체장비',
    },
    {
      id: 'equipment-electrical-design',
      href: '/sources/ncs-semi/equipment-electrical-design/',
      title: '반도체 장비 전장 설계',
      summary: '장비가 쓰는 전기를 계산하고 부품을 골라 하나의 제어반으로 설계하는 일',
      readingTime: 9,
      group: '반도체장비',
    },
    {
      id: 'equipment-board-design',
      href: '/sources/ncs-semi/equipment-board-design/',
      title: '반도체 장비 보드 설계',
      summary: '부품을 고르고 회로·PCB를 설계하고 FPGA에 논리를 심는 일',
      readingTime: 10,
      group: '반도체장비',
    },
    {
      id: 'equipment-system-software',
      href: '/sources/ncs-semi/equipment-system-software/',
      title: '반도체 장비 시스템 소프트웨어 개발',
      summary: '장비를 실제로 움직이는 Library·드라이버·컨트롤러·GUI 소프트웨어를 만드는 일',
      readingTime: 9,
      group: '반도체장비',
    },
    {
      id: 'equipment-utility-software',
      href: '/sources/ncs-semi/equipment-utility-software/',
      title: '반도체 장비 유틸리티 소프트웨어 개발',
      summary: '장비와 통신·진단·데이터를 주고받는 지원 소프트웨어를 개발하는 일',
      readingTime: 9,
      group: '반도체장비',
    },
    {
      id: 'equipment-outsourcing',
      href: '/sources/ncs-semi/equipment-outsourcing/',
      title: '반도체 장비 생산 외주관리',
      summary: '외주업체를 고르고 품질을 검수하고 재고를 알맞게 채우는 공급망 관리',
      readingTime: 11,
      group: '반도체장비',
    },
    {
      id: 'equipment-prototype-evaluation',
      href: '/sources/ncs-semi/equipment-prototype-evaluation/',
      title: '반도체 장비 시제품 성능평가',
      summary: '새로 만든 장비를 조립·설치부터 마라톤 사이클까지 4단계로 검증하는 일',
      readingTime: 10,
      group: '반도체장비',
    },
    {
      id: 'equipment-quality-control',
      href: '/sources/ncs-semi/equipment-quality-control/',
      title: '반도체 장비 품질관리',
      summary: '부품 수입 검사부터 고객 Qualification까지 — 장비 제조사의 품질관리',
      readingTime: 10,
      group: '반도체장비',
    },
    {
      id: 'equipment-customer-support',
      href: '/sources/ncs-semi/equipment-customer-support/',
      title: '반도체 장비 고객 지원',
      summary: '장비 셋업·유지보수·클레임 대응을 맡는 필드 서비스 엔지니어의 일',
      readingTime: 10,
      group: '반도체장비',
    },
    {
      id: 'equipment-mechanical-assembly',
      href: '/sources/ncs-semi/equipment-mechanical-assembly/',
      title: '반도체 장비 기구 조립',
      summary: '도면을 읽고 기초 구조물부터 커버까지 정밀도를 지켜 장비를 조립하는 일',
      readingTime: 11,
      group: '반도체장비',
    },
    {
      id: 'equipment-assembly',
      href: '/sources/ncs-semi/equipment-assembly/',
      title: '반도체 장비 기구 조립 검증',
      summary: '조립한 장비 기구가 정밀도 기준을 만족하는지 검증하는 일',
      readingTime: 10,
      group: '반도체장비',
    },
    {
      id: 'equipment-electrical-assembly',
      href: '/sources/ncs-semi/equipment-electrical-assembly/',
      title: '반도체 장비 전장 조립',
      summary: '장비의 전원·배선·차단기를 안전 규격대로 조립하는 일',
      readingTime: 9,
      group: '반도체장비',
    },
    {
      id: 'equipment-electrical-verification',
      href: '/sources/ncs-semi/equipment-electrical-verification/',
      title: '반도체 장비 전장 조립 검증',
      summary: '배선과 장비 동작이 도면·표준대로 안전한지 측정으로 검증하는 일',
      readingTime: 11,
      group: '반도체장비',
    },
    {
      id: 'optical-equipment-maintenance',
      href: '/sources/ncs-semi/optical-equipment-maintenance/',
      title: '반도체 광학 장비 유지보수',
      summary: '빛으로 두께·먼지·성분을 재는 계측 장비를 셋업하고 관리하는 일',
      readingTime: 10,
      group: '반도체장비',
    },
    {
      id: 'vacuum-plasma-maintenance',
      href: '/sources/ncs-semi/vacuum-plasma-maintenance/',
      title: '반도체 진공 플라스마 장비 유지보수',
      summary: '진공펌프·RF·플라스마 발생부의 원리와 예방정비·고장 대응을 다루는 일',
      readingTime: 9,
      group: '반도체장비',
    },
    {
      id: 'chemical-gas-maintenance',
      href: '/sources/ncs-semi/chemical-gas-maintenance/',
      title: '반도체 케미컬 가스 장비 유지보수',
      summary: '약액·가스 공급 계통을 셋업하고 잔류 가스를 비우고 누출에 대응하는 일',
      readingTime: 11,
      group: '반도체장비',
    },
    {
      id: 'equipment-safety',
      href: '/sources/ncs-semi/equipment-safety/',
      title: '반도체 장비 안전관리',
      summary: '장비를 만들고 세우고 고치는 매 순간 협착·고전압·잔류 가스에서 사람을 지키는 일',
      readingTime: 10,
      group: '반도체장비',
    },
  ],
};

/**
 * 반도체고 교과서 「반도체 기초」 — 공정기초(daegu)의 선행편: 개념·산업·물성·소자.
 * 원자료 `data/school-text/20260415_102949_반도체기초_렛유인_/`를 고등학생 눈높이로 **전면 재작성**
 * (daegu 저작권 원칙 일괄: 원문 문장·도판 미사용, 수치·정의만 근거 + 원저자·발행처 표기).
 * 10모듈 전체 등록 완료 — 등록 순서 = 교과서 목차 순서 = 이전/다음 내비 순서.
 * sections 항목과 `schoolTextMdx.tsx` REGISTRY 로더는 반드시 쌍으로 관리한다
 * (로더 누락 시 실패 모드는 schoolTextMdx.tsx 헤더 주석 참고).
 */
export const HS_SEMI_BASICS: Source = {
  id: 'hs-semicon-basics',
  kind: 'textbook',
  language: 'ko',
  title: '반도체 기초',
  subtitle: '반도체고 교과서 — 개념·산업·물성·소자, 공정기초의 선행편',
  attribution: '조우현·김준호',
  publisher: '렛유인',
  license: 'fair-use',
  order: 4,
  accent: 'school',
  category: 'hs-textbook',
  sections: [
    {
      id: 'semicon-overview',
      href: '/sources/hs-semicon-basics/semicon-overview/',
      title: '반도체 개요',
      summary: '반도체란 무엇인가 — 도체와 부도체 사이, 시스템·메모리·센서로 나뉘는 반도체 제품의 큰 그림',
      readingTime: 11,
      group: '반도체 개념',
    },
    {
      id: 'semicon-industry',
      href: '/sources/hs-semicon-basics/semicon-industry/',
      title: '반도체 산업',
      summary: '5,800억 달러 시장과 밸류체인 — 팹리스·파운드리·OSAT·IDM이 만드는 생태계',
      readingTime: 14,
      group: '반도체 개념',
    },
    {
      id: 'semicon-careers',
      href: '/sources/hs-semicon-basics/semicon-careers/',
      title: '반도체 직무',
      summary: '공정 설계부터 인프라·안전까지 — 반도체 엔지니어의 포지션 지도와 취업 요건',
      readingTime: 10,
      group: '반도체 개념',
    },
    {
      id: 'physical-properties',
      href: '/sources/hs-semicon-basics/physical-properties/',
      title: '반도체 물리적 특성',
      summary: '자유전자와 정공, 실리콘 결정, 그리고 에너지 밴드로 읽는 도체·반도체·부도체',
      readingTime: 13,
      group: '반도체 특성',
    },
    {
      id: 'semicon-fundamentals',
      href: '/sources/hs-semicon-basics/semicon-fundamentals/',
      title: '반도체 기초',
      summary: '진성·외인성 반도체와 도핑, 페르미 레벨, 표동·확산 — 물성의 핵심',
      readingTime: 13,
      group: '반도체 특성',
    },
    {
      id: 'passive-components',
      href: '/sources/hs-semicon-basics/passive-components/',
      title: '수동소자',
      summary: '저항기·축전기·인덕터(R·L·C)의 원리와 반도체 공정에서의 구현',
      readingTime: 9,
      group: '반도체 소자',
    },
    {
      id: 'diode',
      href: '/sources/hs-semicon-basics/diode/',
      title: '다이오드',
      summary: 'PN 접합과 공핍영역, 순방향·역방향, 항복, 그리고 쇼트키·옴 접합',
      readingTime: 13,
      group: '반도체 소자',
    },
    {
      id: 'bjt',
      href: '/sources/hs-semicon-basics/bjt/',
      title: 'BJT',
      summary: '최초의 트랜지스터 — 이미터·베이스·콜렉터와 전류 증폭의 원리',
      readingTime: 9,
      group: '반도체 소자',
    },
    {
      id: 'mosfet',
      href: '/sources/hs-semicon-basics/mosfet/',
      title: 'MOSFET',
      summary: 'MOS 커패시터부터 문턱 전압·단채널 효과, HKMG·FinFET·GAA까지',
      readingTime: 20,
      group: '반도체 소자',
    },
    {
      id: 'cmos-image-sensor',
      href: '/sources/hs-semicon-basics/cmos-image-sensor/',
      title: 'CMOS 이미지 센서',
      summary: '빛을 숫자로 바꾸는 반도체의 눈 — 포토다이오드와 CIS 구조의 진화',
      readingTime: 12,
      group: '반도체 소자',
    },
  ],
};

/**
 * 대구반도체고 교과서 「반도체 공정기초」 — 공정 원리를 교과서 단원 순서 그대로.
 * 원자료 `data/school-text/daegu/`(상업 출판 교재)를 고등학생 눈높이로 **전면 재작성**.
 * 저작권: 원문 문장·도판(244개) 미사용, 수치·정의만 근거로 재서술 + 원저자·발행처 표기.
 * 확장: `src/content/sources/daegu-hs-process/{module}.mdx` 작성 + `daeguMdx.tsx` 로더 등록 +
 * 아래 sections에 목차 순서대로 추가 (등록 순서 = 이전/다음 내비 순서).
 */
export const DAEGU_HS: Source = {
  id: 'daegu-hs-process',
  kind: 'textbook',
  language: 'ko',
  title: '반도체 공정기초',
  subtitle: '대구반도체고 교과서 — 공정 원리를 단원 순서 그대로',
  attribution: '조우현·김준호',
  publisher: '렛유인',
  license: 'fair-use',
  order: 5,
  accent: 'school',
  category: 'hs-textbook',
  sections: [
    {
      id: 'process-overview',
      href: '/sources/daegu-hs-process/process-overview/',
      title: '반도체 공정 개요',
      summary: '8대 공정과 전공정·후공정, 웨이퍼 제작, 클린룸 — 반도체 공정의 큰 그림',
      readingTime: 8,
      group: '반도체 공정 개념',
    },
    {
      id: 'equipment-parameters',
      href: '/sources/daegu-hs-process/equipment-parameters/',
      title: '공정 설비와 파라미터',
      summary: '챔버·진공·플라즈마로 배우는 공정 설비의 작동 원리',
      readingTime: 15,
      group: '반도체 공정 개념',
    },
    {
      id: 'photo',
      href: '/sources/daegu-hs-process/photo/',
      title: '포토 공정',
      summary: '포토마스크·감광제·노광부터 다중패턴·EUV까지, 포토 공정 전 과정',
      readingTime: 18,
      group: '반도체 공정 Ⅰ',
    },
    {
      id: 'etch',
      href: '/sources/daegu-hs-process/etch/',
      title: '식각 공정',
      summary: '습식·건식식각, 플라즈마·RIE, 고밀도 플라즈마와 원자층식각(ALE)까지',
      readingTime: 20,
      group: '반도체 공정 Ⅰ',
    },
    {
      id: 'thin-film',
      href: '/sources/daegu-hs-process/thin-film/',
      title: '박막 공정',
      summary: 'PVD·CVD·ALD로 박막을 쌓는 원리와 품질을 가르는 세 잣대',
      readingTime: 14,
      group: '반도체 공정 Ⅰ',
    },
    {
      id: 'metallization',
      href: '/sources/daegu-hs-process/metallization/',
      title: '금속 배선 공정',
      summary: '실리사이드부터 구리 전해 도금까지, 배선 재료의 변천사',
      readingTime: 13,
      group: '반도체 공정 Ⅰ',
    },
    {
      id: 'oxidation',
      href: '/sources/daegu-hs-process/oxidation/',
      title: '산화 공정',
      summary: '열산화막의 특성·성장 원리와 산화·질화 공정 장비 이해하기',
      readingTime: 12,
      group: '반도체 공정 Ⅱ',
    },
    {
      id: 'doping',
      href: '/sources/daegu-hs-process/doping/',
      title: '도핑 공정',
      summary: '확산·이온주입·에피택시로 실리콘에 전기 성질을 심는 세 가지 방법',
      readingTime: 17,
      group: '반도체 공정 Ⅱ',
    },
    {
      id: 'cmp',
      href: '/sources/daegu-hs-process/cmp/',
      title: 'CMP 공정',
      summary: '슬러리와 패드로 웨이퍼를 갈아 평평하게 만드는 CMP 공정',
      readingTime: 12,
      group: '반도체 공정 Ⅱ',
    },
    {
      id: 'cleaning',
      href: '/sources/daegu-hs-process/cleaning/',
      title: '세정 공정',
      summary: '웨이퍼 오염을 씻어내는 습식·건식 세정 기술의 원리와 비교',
      readingTime: 11,
      group: '반도체 공정 Ⅱ',
    },
  ],
};

export const SOURCES: Source[] = [EPI_BOOK, OSHA_SCS, NCS_SEMI, HS_SEMI_BASICS, DAEGU_HS];

export function getOrderedSources(): Source[] {
  return [...SOURCES].sort((a, b) => a.order - b.order);
}

export function getSource(id: string): Source | undefined {
  return SOURCES.find((s) => s.id === id);
}

export function getSourceSection(
  sourceId: string,
  sectionId: string,
): { source: Source; section: SourceSection } | undefined {
  const source = getSource(sourceId);
  if (!source) return undefined;
  const section = source.sections.find((s) => s.id === sectionId);
  if (!section) return undefined;
  return { source, section };
}
